# Generated by Django 4.2.6 on 2023-10-27 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Card',
            new_name='Car',
        ),
    ]
