# Generated by Django 4.2.6 on 2023-10-31 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_mileage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mileage',
            options={'verbose_name': 'пробег', 'verbose_name_plural': 'пробег'},
        ),
    ]
