# Generated by Django 4.2.6 on 2023-11-01 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_alter_mileage_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mileage',
            options={'verbose_name': 'пробег', 'verbose_name_plural': 'пробег'},
        ),
    ]
