# Generated by Django 4.2.6 on 2023-11-01 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0011_alter_mileage_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mileage',
            name='moto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mileage', to='vehicle.moto', verbose_name='мотоцикл'),
        ),
    ]
