# Generated by Django 4.2.7 on 2023-11-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0015_remove_car_amount_car_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
